astarte-platform/astarte-message-hub

.github/workflows/build.yaml
.github/workflows/codecov.yaml
Cargo.lock
Cargo.toml
README.md
build.rs
proto/astarteplatform/msghub/astarte_message.proto
proto/astarteplatform/msghub/astarte_type.proto
proto/astarteplatform/msghub/interface.proto
proto/astarteplatform/msghub/message_hub_service.proto
proto/astarteplatform/msghub/node.proto
src/lib.rs

- Add tonic lib and proto file
- Define Attach method.
- Define Send Method.
- Define Remove Method.
Closes #3 .

gRPC Service definition

---

codecov.yml

Add missing codecov configuration file.
The flag set in the file reduces codecov patch warning noise.
Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

Add missing codecov.yml file

---

Cargo.lock
Cargo.toml
README.md
build.rs
proto/astarteplatform/msghub/config.proto
src/config/file.rs
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/error.rs
src/lib.rs
src/main.rs
src/types.rs

- Add a way to retrieve the configurations from a file
- Add the capability to set a new configuration file using HTTP APIs
- Add the capability to set a new configuration file using protobuf APIs
Close #27

Add support to external-provided configs

---

.github/workflows/build.yaml
src/astarte_message_hub.rs
src/astarte_sdk_types.rs
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/data/astarte_provider.rs
src/data/mock_astarte.rs
src/lib.rs
src/main.rs
src/types.rs

Add clippy to CI

---

src/data/astarte_handler.rs

Implement `new()` for Astarte handler

---

src/astarte_message_hub.rs
src/data/astarte.rs
src/data/astarte_handler.rs
src/data/mock_astarte_sdk.rs

Implement Detach method

---

src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/error.rs
src/lib.rs
src/main.rs

Implementation for the message hub server.
Closes #75.

Message hub server

---

.reuse/dep5
README.md
examples/README.md
examples/client/README.md
examples/client/interfaces/org.astarte-platform.rust.examples.datastream.DeviceDatastream.json
examples/client/interfaces/org.astarte-platform.rust.examples.datastream.ServerDatastream.json
examples/client/main.rs
src/proto_message_hub.rs

docs(example): add  a client example

---

.reuse/dep5
CHANGELOG.md
Cargo.lock
Cargo.toml

Initial release of the Astarte Message Hub v0.5.0

Prepare release 0.5.0

---

src/config/file.rs
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/device.rs

Remove refers to edgehog license

---

.github/workflows/build.yaml
.github/workflows/codecov.yaml
Cargo.lock
Cargo.toml
README.md
src/astarte_device_sdk_types.rs
src/astarte_message_hub.rs
src/data/astarte_handler.rs
src/data/mock_astarte_sdk.rs
src/error.rs
src/main.rs
src/types.rs

- Prepare next dev cycle to 0.6.0-dev
- Bump Rust to 1.66.1 version

Bump Astarte Device SDK to 0.6.0

---

Cargo.lock
Cargo.toml
src/error.rs
src/main.rs

refactor(store): use sqlite rather than memory store

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/ARCHITECTURE.md
e2e-test/src/message_hub.rs
examples/client/main.rs
src/main.rs
src/server.rs

Close #197 
Close #198 
Close #222

feat(metadata): add check for Node ID on gRPC metadata

---

Cargo.lock
Cargo.toml
e2e-test/src/message_hub.rs
src/astarte/handler.rs
src/astarte/mod.rs
src/cache.rs
src/config/file.rs
src/config/mod.rs
src/error.rs
src/lib.rs
src/main.rs
src/server.rs

Cache the introspection of the nodes when it attaches.

feat(introspection): implement cache introspection

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/ARCHITECTURE.md
src/server.rs

Use Empty type rather than Node to detach a Node

Refactor detach

---

scripts/docker/Dockerfile
scripts/docker/build.sh

Fix git script and add missing sqlite dependencies to Dockerfile.

fix(docker): add missing dependencies to docker

---

src/server.rs

Log error when a node send incorrect data types

---

.github/workflows/check.yaml
.github/workflows/e2e-test.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
e2e-test/src/api.rs
e2e-test/src/device_sdk.rs
e2e-test/src/interfaces.rs
e2e-test/src/main.rs
e2e-test/src/message_hub.rs
examples/client/main.rs
scripts/e2e.sh
src/astarte/handler.rs
src/cache.rs
src/error.rs
src/main.rs
src/server.rs

Requires these PR to be merged first
- ~[proto fix typo](https://github.com/astarte-platform/astarte-message-hub-proto/pull/74)~
- ~[sdk fix typo](https://github.com/astarte-platform/astarte-device-sdk-rust/pull/435)~

Reflect new message-hub protobuf definitions

---

src/astarte/handler.rs
src/astarte/mod.rs
src/error.rs
src/server.rs

fix(props): retrieve only props in the node introspection

---

.github/workflows/ci.yaml
.github/workflows/multi-platform.yaml

feat(ci): add checks for windows
