Cargo.lock
Cargo.toml
proto/astarteplatform/msghub/astarte_type.proto
src/lib.rs
src/types.rs

- Implements type conversion from all scalar and vector Rust type defined in the `astarte_type` proto file.
- Add tests on AstarteDataType conversion trait.
- Use plural names for repeated fields.
Closes #10.

Implement type conversion for AstarteDataType

---

Cargo.lock
Cargo.toml
build.rs
src/astarte_sdk_types.rs
src/error.rs
src/types.rs

- **Implement conversion type from AstarteSDK types to Astarte proto types.**
- **Enable serde Serialize/Deserialize on Astarte proto types.**
At this moment proto-types doesn't support serde on well known types, so we changed proto-types crate to pbjson-types in order to support them.
pbjson-types also supports conversion directly from Datetime, which is also the date library used by Astarte SDK, deleting the double conversion from DateTime to SystemTime and then to Timestamp.
- Downgrade time dependency to 0.3.13 that is last version compatible wit Rust 1.58.1.
Closes #11 .

Implement type conversion for Astarte SDK Type

---

Cargo.lock
Cargo.toml
src/astarte_message_hub.rs
src/data/astarte.rs
src/data/astarte_provider.rs
src/data/mock_astarte.rs
src/data/mod.rs
src/lib.rs
src/main.rs

- Add `AstartePublisher` and `AstarteSubscriber` traits. This allows the AstarteSDK to be encapsulated behind Publisher/Subscriber traits, decoupling the collection and delivery of messages from the communication with Astarte broker and also improves the testability of the project.
- The attach method returns an `AttachStream` type,where will be redirected all Astarte Data event received by the Node Attached.
- Add node client example
Closes #12, closes #28.

Implement Attach node method

---

build.rs
src/astarte_message_hub.rs
src/data/astarte_provider.rs
src/data/mock_astarte.rs
src/error.rs
src/types.rs

- Add implementation of proto Send  method.
- Add implementation of AstartePublisher.
- Add `error(transparent)` on some errors to forward the source and Display methods straight through to an underlying error without adding additional error.
- Remove `PartiEq` derive because not all errors implements it.
- Use `matches!` to compare the AstarteMessageHubError enum values.
From AstarteDeviceSDK 0.5.1 for publishing an aggregate the AstarteAggregate macro will be used, so I removed serde from `proto` types generation.
Closes #13 .

Add Send method

---

Cargo.toml

The `rust-version` field has been added in the `cargo.toml` file to help with linting.
When running clippy with the latest stable version of Rust, the warnings related to newer features are suppressed.
As can be seen [here](https://github.com/rust-lang/rust-clippy#specifying-the-minimum-supported-rust-version), different approaches can be used to specify the minimum supported Rust version of clippy.
The chosen one seems the least invasive in the sources and the more likely to be supported in the future.

Add rust-version to cargo configuration

---

src/astarte_message_hub.rs
src/data/astarte.rs
src/data/astarte_handler.rs
src/data/mock_astarte_sdk.rs

Call the `run()` function for the message hub in a separated `tokio` task spawned inside the MessageHub `new()` function.
Close #74.

Run the AstarteHandler in the MessageHub

---

src/astarte_device_sdk_types.rs
src/types.rs

-  Add type conversion from `proto::AstarteMessage` to `sdk::AstarteDeviceDataEvent`
- Add type conversion from `sdk::AstarteType` to `proto::Payload`
- Add type conversion from Map of AstarteType to `proto::Payload`

Improve type conversion

---

Cargo.lock
Cargo.toml
src/config/mod.rs
src/main.rs

Adds two CLI options that can be used to configure the message hub:
- `toml`: A path to a valid `.toml` file which will then be used to extract the configuration.
- `store_directory`: Path to an existing directory. Is used by the HTTP and ProtoBuf servers to store the received configuration.
The two options are mutually exclusive and should not be used together.
If neither option is provided, the message hub will fallback to searching for a `.toml` file in the base locations.
Closes #89

Implement CLI options

---

Cargo.lock
Cargo.toml
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/main.rs

Add a method to obtain the credentials if not present in the configurations. The credentials are stored in the current working directory or in a directory passed from the command line.
If the credentials are not present, it will try to register the device on Astarte with the pairing token.
Added `tempfile` crate to test using the file system.
Closes #96 and #103

feat(config): persist credentials to file

---

src/config/file.rs
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/error.rs
src/main.rs

The validation function now returns a ConfigValidationError, which contains more information about the error. This is useful for the user to understand what's wrong with the configuration file.

feat(config): add a more explicative error to the validation

---

Cargo.toml
build.rs

Since docs.rs uses Ubuntu LTS the protobuf version is 3.12, which doesn't support optional fields. This patch adds a feature to build the documentation on docs.rs, which adds the `--experimental_allow_proto3_optional` flag to protoc.

 fix(docsrs): add a feature to build the docs on docs.rs

---

Cargo.toml
build.rs

This uses the environment variable `DOCS_RS` to detect if the docs are being built on docs.rs, and if so, it adds the `--experimental_allow_proto3_optional` flag to the protoc command.

 fix(docs): fix building docs on docs.rs 

---

Cargo.lock

Bump anyhow to 1.0.71
Bump async-stream to 0.3.5
Bump base64 to 0.21.2

Line up dependencies versions to edgehog-device

---

.gitignore
CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
examples/README.md
examples/message-hub-config.toml
src/astarte_device_sdk_types.rs
src/config/file.rs
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/main.rs
src/types.rs

This will expose the connection timeout and keep alive from the new version of the Astarte SDK.
The options related to the Astarte MQTT connection have been moved to a separate struct, while still supporting the old fields.
Closes #200

feat(options): bump astarte sdk to v0.5.2 and expose conneciton timeout and keepalive

---

README.md
src/main.rs

Don't error if the interface directory is missing.
Reverti the a regression that slipt into by https://github.com/astarte-platform/astarte-message-hub/pull/215 we should be able to start the message hub without interfaces.

fix(interface):  make the interface dir not error

---

Cargo.lock
Cargo.toml

Also update time dependency to solve CI nightly doc warning

Bump sdk v0.8.2

---

.github/workflows/ci.yaml

Since the hosted DCO app is currently down we will use a forked version, implemented as a Github Action. This is a temporary fix until the projects resolves the hosting issues.

refactor(ci): use custom DCO action

---

src/main.rs

The introspection was never stored since the directory was never created.

fix(caching): create introspection cache directory

---

CHANGELOG.md
Cargo.lock
docs/ARCHITECTURE.md
src/astarte/handler.rs

When a node attaches, we will send all the server properties that the
node is subscribed to. This will keep the properties in sync since it
can have missed some of them when it was disconnected.
Closes #211

 feat(props): send all server props on attach 

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docs/ARCHITECTURE.md
e2e-test/src/device_sdk.rs
e2e-test/src/message_hub.rs
examples/client/main.rs
src/astarte/handler.rs
src/astarte/mod.rs
src/main.rs
src/server.rs

Update the Message Hub server error handling after the Message Hub proto changes.
Also, this PR Reflects the astarte-message-hub-proto changes related to the node id information, which has been removed from the attach rpc parameter (since it is transmitted inside the grpc metadata).
Closes #210

Handle generic Message Hub proto errors 

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Remove display doc patch since fixed upstream.

chore(deps): bump astarte-device-sdk to v0.9.6

---

CHANGELOG.md
README.md
src/cli.rs

Add a new cli flag `--pairing-url` and `MSGHUB_PAIRING_URL` env as configuration options.
Closes #333

fix(config): expose the `pairing_url` to the cli and env

---

Cargo.lock
Cargo.toml
e2e-test/src/main.rs
examples/client/main.rs
src/config/http.rs
src/config/mod.rs
src/config/protobuf.rs
src/main.rs
src/server.rs

By using the tracing subscriber Registry layer we are able to better track active spans, thus fixing some of the logs in which the statement was an empty line with info level

refactor(log): use tracing_subscriber for a better log

---

Cargo.toml

Solve the error depicted [here](https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies)

fix(deps): specify version for aws-lc-rs and rusqlite to avoid cargo publish error
